from typing import List, Dict, Any, Optional, Union, cast
from .constants import DEFAULT_THRESHOLDS
from .types import FileAnalysisResult, AdvisorFileResult
from .remediation import generate_prompts_section, generate_recommendations_report

__all__ = ["generate_recommendations_report", "generate_prompts_section"]


def _generate_summary_section(
    final_score: float,
    profile: Dict[str, Any],
    project_issues: Optional[List[str]],
    version: str = "0.0.0",
    summary_stats: Optional[Dict[str, int]] = None,
) -> str:
    """
    Creates the executive summary section of the report.
    """
    # RESOLUTION: Combined versioned header with detailed beta summary stats
    summary = f"# Agent Scorecard Report v{version}\n\n"
    profile_desc = profile.get("description", "Generic").split(".")[0]
    summary += f"**Target Agent Profile:** {profile_desc}\n"
    status_str = "PASS" if final_score >= 70 else "FAIL"
    summary += f"**Overall Score: {final_score:.1f}/100** - {status_str}\n\n"

    if final_score >= 70:
        summary += "✅ **Status: PASSED** - This codebase is Agent-Ready.\n\n"
    else:
        summary += "❌ **Status: FAILED** - This codebase needs improvement for AI Agents.\n\n"

    if summary_stats:
        summary += "### 📊 Project Summary\n"
        summary += f"- **Total Files Analyzed:** {summary_stats.get('total_files', 0)}\n"
        summary += f"- **Total Red Functions:** {summary_stats.get('red_functions', 0)} 🔴\n"
        summary += f"- **Total Yellow Functions:** {summary_stats.get('yellow_functions', 0)} 🟡\n\n"

    if project_issues:
        summary += "### ⚠️ Project Issues\n"
        for issue in project_issues:
            summary += f"- {issue}\n"
        summary += "\n"
    return summary


def _generate_acl_section(
    stats: Union[List[FileAnalysisResult], List[Dict[str, Any]]],
    thresholds: Dict[str, Any],
    sort_by: str = "acl",
    top_limit: Optional[int] = None,
) -> str:
    """
    Analyzes and reports on units with high Agent Cognitive Load using AST-depth weights.
    """
    acl_yellow = thresholds.get("acl_yellow", DEFAULT_THRESHOLDS["acl_yellow"])
    acl_red = thresholds.get("acl_red", DEFAULT_THRESHOLDS["acl_red"])

    targets = "## 🎯 Top Refactoring Targets (Agent Cognitive Load (ACL))\n\n"
    targets += f"ACL = (Depth * 2) + (Complexity * 1.5) + (LOC / 50). Target: ACL <= {acl_yellow}.\n\n"

    all_functions = []
    for f_res in stats:
        metrics = f_res.get("function_metrics", [])
        for m in metrics:
            all_functions.append({**m, "file": f_res["file"]})

    # --- RESOLUTION: SORTING & LIMITING LOGIC ---
    high_acl_functions = [
        fn for fn in all_functions if cast(float, fn.get("acl", 0)) > acl_yellow
    ]

    sort_key = sort_by if sort_by in ["acl", "loc", "complexity"] else "acl"
    sorted_funcs = sorted(
        high_acl_functions, key=lambda x: x.get(sort_key, 0), reverse=True
    )

    if top_limit is not None:
        sorted_funcs = sorted_funcs[:top_limit]
    # --- END SORTING & LIMITING ---

    if sorted_funcs:
        targets += "| Function | File | 🧠 ACL | Status |\n"
        targets += "|----------|------|--------|--------|\n"
        for fn in sorted_funcs:
            acl_val = cast(float, fn.get("acl", 0))
            status = "🔴 Red" if acl_val > acl_red else "🟡 Yellow"
            targets += f"| `{fn['name']}` | `{fn['file']}` | {acl_val:.1f} | {status} |\n"
        targets += "\n"
    else:
        targets += f"✅ All functions meet the Agent Cognitive Load (ACL) target of <= {acl_yellow}.\n\n"
    return targets

# ... [generate_type_safety_section and generate_file_table_section remain unchanged] ...

def generate_markdown_report(
    stats: Union[List[FileAnalysisResult], List[Dict[str, Any]]],
    final_score: float,
    path: str,
    profile: Dict[str, Any],
    project_issues: Optional[List[str]] = None,
    thresholds: Optional[Dict[str, Any]] = None,
    report_style: str = "actionable",
    version: str = "0.0.0",
    sort_by: str = "acl",
    top_limit: Optional[int] = None,
    summary: Optional[Dict[str, int]] = None,
) -> str:
    """
    Orchestrates the Markdown report generation using customizable styles.
    """
    if thresholds is None:
        thresholds = DEFAULT_THRESHOLDS.copy()

    style_map = {"full": "detailed", "actionable": "summary", "collapsed": "quiet"}
    verbosity = style_map.get(report_style, "summary")

    summary_text = _generate_summary_section(
        final_score, profile, project_issues, version=version, summary_stats=summary
    )

    if verbosity == "quiet":
        return summary_text + "\n---\n*Generated by Agent-Readiness-Scorecard*"

    targets = _generate_acl_section(stats, thresholds, sort_by, top_limit)
    types_section = _generate_type_safety_section(stats, thresholds, verbosity)
    prompts = generate_prompts_section(stats, thresholds, project_issues)
    table = _generate_file_table_section(stats, verbosity)

    return (
        summary_text
        + targets
        + types_section
        + prompts
        + "\n"
        + table
        + "\n---\n*Generated by Agent-Readiness-Scorecard*"
    )